src/accounts/urls.py
"""Defines URL patterns for accounts app"""

from django.urls import path

from django.contrib.auth.views import LoginView, LogoutView
from .views import UserRegistrationView

app_name='accounts'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('register/', UserRegistrationView.as_view(), name='register'),
]

src/discuss/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # URLs of accounts app.
    path('', include('accounts.urls')), 
    # URLs for links app
    path('', include('links.urls')),
]

src/links/urls.py
"""Defines URL patterns for links app."""

from .views import HomeView, NewSubmissionView, SubmissionDetailView, NewCommentView, NewCommentReplyView, UpvoteSubmissionView, RemoveUpvoteFromSubmissionView
from django.urls import path

app_name='links'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('new-submission/', NewSubmissionView.as_view(), name='new-submission'),
    path('submission/<int:pk>/', SubmissionDetailView.as_view(), name='submission-detail'),
    path('new-comment/', NewCommentView.as_view(), name='new-comment'),
    path('new-comment-reply/', NewCommentReplyView.as_view(), name='new-comment-reply'),
    path('upvote/<int:link_pk>/', UpvoteSubmissionView.as_view(), name='upvote-submission'),
    path('upvote/<int:link_pk>/remove/', RemoveUpvoteFromSubmissionView.as_view(), name='remove-upvote')
]

src/links/models.py
from django.db import models
from django.contrib.auth.models import User


class Link(models.Model):
    title = models.CharField(max_length=100)
    url = models.URLField()

    submitted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    upvotes = models.ManyToManyField(User, related_name='votes')

    submitted_on = models.DateTimeField(auto_now_add=True, editable=False)

class Comment(models.Model):
    body = models.TextField()

    commented_on = models.ForeignKey(Link, on_delete=models.CASCADE)
    in_reply_to = models.ForeignKey('self', null=True, on_delete=models.CASCADE)

    commented_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add = True, editable = False)

src/links/forms.py
from django import forms

from links.models import Comment

from django_recaptcha.fields import ReCaptchaField

class CommentModelForm(forms.ModelForm):
    link_pk = forms.IntegerField(widget=forms.HiddenInput) # widget is used for stylings
    parent_comment_pk = forms.IntegerField(widget=forms.HiddenInput, required=False)

    captcha = ReCaptchaField()
    
    class Meta:
        model = Comment
        fields = {
            'body',
        }

src/links/views.py
from django.utils import timezone

from typing import Any
from django.http import HttpResponse
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http.response import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, TemplateView, DetailView, View

from links.models import Link, Comment
from links.forms import CommentModelForm


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        ctx = super(HomeView, self).get_context_data(**kwargs)

        now = timezone.now()
        submissions = Link.objects.all()
        for submission in submissions:
            num_votes = submission.upvotes.count()
            num_comments = submission.comment_set.count()

            date_diff = now - submission.submitted_on
            number_of_days_since_submission = date_diff.days

            submission.rank = num_votes + num_comments - number_of_days_since_submission
        
        sorted_submissions = sorted(submissions, key=lambda x: x.rank, reverse=True)
        ctx['submissions'] = sorted_submissions

        return ctx


class NewSubmissionView(CreateView):
    model = Link
    fields = (
        'title', 'url'
    )   

    template_name= 'new_submission.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(NewSubmissionView, self).dispatch(request, *args, **kwargs)
    
    # defined and not inherited from CreateView because we need to set submitted_by field
    def form_valid(self, form):
        new_link = form.save(commit=False)          
        new_link.submitted_by = self.request.user
        new_link.save()

        self.object = new_link
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        return reverse('links:submission-detail', kwargs={'pk': self.object.pk})
    
    
class SubmissionDetailView(DetailView):
    model = Link
    template_name = 'submission_detail.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super(SubmissionDetailView, self).get_context_data(**kwargs)

        submission_comments = Comment.objects.filter(commented_on=self.object, in_reply_to__isnull=True)
        # in_reply_to__isnull allows only the comments that are no a reply

        ctx['comments'] = submission_comments

        ctx['comment_form'] = CommentModelForm(initial={'link_pk':self.object.pk})

        return ctx
    


class NewCommentView(CreateView):
    form_class = CommentModelForm
    http_method_names = ('post',)
    template_name = 'comment.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(NewCommentView, self).dispatch(*args, **kwargs)

    def form_valid(self, form) -> HttpResponse:
        parent_link = Link.objects.get(pk=form.cleaned_data['link_pk'])
        new_comment = form.save(commit=False)
        new_comment.commented_on = parent_link
        new_comment.commented_by = self.request.user

        new_comment.save()

        return HttpResponseRedirect(reverse('links:submission-detail', kwargs={'pk': parent_link.pk}))
    
    def get_initial(self):
        initial_data = super(NewCommentView, self).get_initial()
        initial_data['link_pk'] = self.request.GET['link_pk']

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super(NewCommentView, self).get_context_data(**kwargs)
        ctx['submission'] = Link.objects.get(pk=self.request.GET['link_pk'])

        return ctx


class NewCommentReplyView(CreateView):
    form_class = CommentModelForm
    template_name = 'comment_reply.html' # a better way to do this is to use interactive javascript

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(NewCommentReplyView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super(NewCommentReplyView, self).get_context_data(**kwargs)
        ctx['parent_comment'] = Comment.objects.get(pk=self.request.GET['parent_comment_pk'])

        return ctx
    
    """
    initial_data: initial data created by an empty form
    allows changing initial data without trigerring validation so as to avoid exceptions
    if the initial data was changed directly, we could have received invalid form errors.
    """
    def get_initial(self) -> dict[str, Any]:
        initial_data = super(NewCommentReplyView, self).get_initial()

        link_pk = self.request.GET['link_pk']
        initial_data['link_pk'] = link_pk

        parent_comment_pk = self.request.GET['parent_comment_pk']
        initial_data['parent_comment_pk'] = parent_comment_pk

        # initial_data is mutable, therefore even if the initial_data was stored under an another name in the original form
        # the previous line would work as expected
 
        return initial_data
    
    def form_valid(self, form):
        parent_link = Link.objects.get(pk=form.cleaned_data['link_pk'])
        parent_comment = Comment.objects.get(pk=form.cleaned_data['parent_comment_pk'])

        new_comment = form.save(commit=False)
        new_comment.commented_on = parent_link
        new_comment.in_reply_to = parent_comment
        new_comment.commented_by = self.request.user

        new_comment.save()

        return HttpResponseRedirect(reverse('links:submission-detail', kwargs={'pk': parent_link.pk}))
    

class UpvoteSubmissionView(View):
    def get(self, request, link_pk, **kwargs):
        link = Link.objects.get(pk=link_pk)
        link.upvotes.add(request.user)

        return HttpResponseRedirect(reverse('links:home'))
    

class RemoveUpvoteFromSubmissionView(View):
    def get(self, request, link_pk, **kwargs):
        link = Link.objects.get(pk=link_pk)
        link.upvotes.remove(request.user)

        return HttpResponseRedirect(reverse('links:home'))

src/links/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />

    <title>Discuss - Share and Disucss your favourite web pages</title>
</head>
<body>
    {% block header %}
    {% endblock header %}
    
    <nav>
        <ul>
            <li><a href="{% url 'links:home' %}">Home</a></li>
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'links:new-submission' %}">Submit New Link</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            <li><a href="{% url 'accounts:register' %}">Create New Account</a></li>
            {% endif %}
        </ul>
    </nav>

    {% block content %}
    {% endblock %}
</body>
</html>

src/links/templates/comment.html
{% extends "base.html" %}

{% block header %}
    <h1>New Comment</h1>
{% endblock header %}

{% block content %}
    <p>
        <b>You are commenting on </b>
        <a href="{% url 'links:submission-detail' pk=submission.pk %}">{{ submission.title }}</a>
    </p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Post Comment" />
    </form>
{% endblock content %}

src/links/templates/comment_reply.html
{% extends "base.html" %}

{% block header %}
    <h1>Reply to comment</h1>
{% endblock header %}

{% block content %}
    <p>
        <b>You are replying to:</b>
        <i>{{ parent_comment.body }}</i>
    </p>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit Reply" />
    </form>
{% endblock content %}

src/links/templates/home.html
{% extends 'base.html' %}

{% block header %}
    <h1>Welcome to Discuss</h1>
    <h2>Submissions</h2>
{% endblock header %}

{% block content %}
    <ul>
        {% for submission in submissions %}
            <li>
                {% if request.user in submission.upvotes.all %}
                    <a href="{% url 'links:remove-upvote' link_pk=submission.pk %}">Remove Upvote</a>
                {% else %}
                    <a href="{% url 'links:upvote-submission' link_pk=submission.pk %}">Upvote</a>
                {% endif %}

                <a href="{{ submission.url }}" target="_blank">
                    {{ submission.title }}
                </a>
                <i><a href="{% url 'links:submission-detail' pk=submission.pk %}">Comments</a></i>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

src/links/templates/new_submission.html
{% extends 'base.html' %}

{% block header %}
<h1>New Submission</h1>
{% endblock header %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock content %}

src/links/templates/submission_detail.html
{% extends "base.html" %}

{% block header %}
<h1><a href="{{ object.url }}" target="_blank">{{ object.title }}</a></h1>
{% endblock header %}

{% block content %}
    <p>submitted by: <b>{{ object.submitted_by.username }}</b></p>
    <p>submitted on: <b>{{ object.submitted_on }}</b></p>

    <p>
        <b>New Comment</b>
        <form action="{% url 'links:new-comment' %}?link_pk={{ object.pk }}" method="post">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <input type="submit" value="Comment" />
        </form>
    </p>

    <p>
        <b>Comments</b>
        <ul>
            {% for comment in comments %}
                <li>{{ comment.body }} 
                    (<a href="{% url 'links:new-comment-reply' %}?
                    link_pk={{ object.pk }}
                    &amp;parent_comment_pk={{ comment.pk }}">Reply</a>)
                    
                    {% if comment.comment_set.exists %}
                    <ul>
                        {% for reply in comment.comment_set.all %}
                            <li>{{ reply.body }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </p>
{% endblock content %}